vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("n", ">", ">>_")
vim.keymap.set("n", "<", "<<_")
vim.keymap.set("n", "<leader>s-", ":split<CR><C-w>j", { silent = true })
vim.keymap.set("n", "<leader>s|", ":vsplit<CR><C-w>l", { silent = true })
vim.keymap.set("n", "Y", '"+y', { noremap = true })
vim.keymap.set("v", "Y", '"+y', { noremap = true })
